latest test results. JS=passing all tests, CS=failing to compile (see notes below), swf=4 tests failing (but can't scroll trace log to see!)
CS error relates to (0).@value code
error CS1061: Type `int' does not contain a definition for `value' and
no extension method `value' of type `int' could be found. Are you
missing an assembly reference?